-- ==========================================
-- 01_schema.sql (PostgreSQL)
-- Схема БД информационной системы библиотеки
-- ==========================================

DROP TABLE IF EXISTS book_faculty CASCADE;
DROP TABLE IF EXISTS book_loans CASCADE;
DROP TABLE IF EXISTS app_users CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS book_authors CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS authors CASCADE;
DROP TABLE IF EXISTS publishers CASCADE;
DROP TABLE IF EXISTS branches CASCADE;
DROP TABLE IF EXISTS faculties CASCADE;

-- Справочник издательств
CREATE TABLE publishers (
    id_publisher BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(200) NOT NULL UNIQUE
);

-- Справочник авторов
CREATE TABLE authors (
    id_author  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name  VARCHAR(250) NOT NULL UNIQUE
);

-- Справочник филиалов
CREATE TABLE branches (
    id_branch BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(200) NOT NULL UNIQUE
);

-- Справочник факультетов
CREATE TABLE faculties (
    id_faculty BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(200) NOT NULL UNIQUE
);

-- Пользователи системы: гость работает без записи, client/admin хранятся здесь.
CREATE TABLE app_users (
    id_user       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(250) NOT NULL,
    email         VARCHAR(250) NOT NULL UNIQUE,
    password_salt VARCHAR(100) NOT NULL,
    password_hash VARCHAR(128) NOT NULL,
    role          VARCHAR(20) NOT NULL DEFAULT 'client',
    id_faculty    BIGINT,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_app_users_role CHECK (role IN ('client', 'admin')),
    CONSTRAINT fk_app_users_faculty FOREIGN KEY (id_faculty) REFERENCES faculties(id_faculty)
);

-- Основная таблица книг
-- Поле id_publisher добавлено для фильтрации по издательству на UI.
CREATE TABLE books (
    id_book              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                VARCHAR(300) NOT NULL,
    publication_year     INTEGER,
    pages_count          INTEGER,
    illustrations_count  INTEGER,
    price                NUMERIC(10, 2),
    id_publisher         BIGINT,
    CONSTRAINT fk_books_publisher FOREIGN KEY (id_publisher) REFERENCES publishers(id_publisher),
    CONSTRAINT ck_books_publication_year CHECK (publication_year BETWEEN 1500 AND 3000),
    CONSTRAINT ck_books_pages_count CHECK (pages_count IS NULL OR pages_count >= 1),
    CONSTRAINT ck_books_illustrations_count CHECK (illustrations_count IS NULL OR illustrations_count >= 0),
    CONSTRAINT ck_books_price CHECK (price IS NULL OR price >= 0)
);

-- Связь many-to-many между книгами и авторами
CREATE TABLE book_authors (
    id_book    BIGINT NOT NULL,
    id_author  BIGINT NOT NULL,
    CONSTRAINT pk_book_authors PRIMARY KEY (id_book, id_author),
    CONSTRAINT fk_book_authors_book FOREIGN KEY (id_book) REFERENCES books(id_book),
    CONSTRAINT fk_book_authors_author FOREIGN KEY (id_author) REFERENCES authors(id_author)
);

-- Инвентарь книг по филиалам
CREATE TABLE inventory (
    id_inventory  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_book       BIGINT NOT NULL,
    id_branch     BIGINT NOT NULL,
    copies_count  INTEGER NOT NULL DEFAULT 0,
    times_issued  INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_inventory_book FOREIGN KEY (id_book) REFERENCES books(id_book),
    CONSTRAINT fk_inventory_branch FOREIGN KEY (id_branch) REFERENCES branches(id_branch),
    CONSTRAINT uq_inventory_book_branch UNIQUE (id_book, id_branch),
    CONSTRAINT ck_inventory_copies CHECK (copies_count >= 0),
    CONSTRAINT ck_inventory_times_issued CHECK (times_issued >= 0)
);

-- Связь книги и факультета в рамках конкретного филиала
CREATE TABLE book_faculty (
    id_book     BIGINT NOT NULL,
    id_branch   BIGINT NOT NULL,
    id_faculty  BIGINT NOT NULL,
    CONSTRAINT pk_book_faculty PRIMARY KEY (id_book, id_branch, id_faculty),
    CONSTRAINT fk_book_faculty_book FOREIGN KEY (id_book) REFERENCES books(id_book),
    CONSTRAINT fk_book_faculty_branch FOREIGN KEY (id_branch) REFERENCES branches(id_branch),
    CONSTRAINT fk_book_faculty_faculty FOREIGN KEY (id_faculty) REFERENCES faculties(id_faculty)
);

-- История выдачи книг студентам.
CREATE TABLE book_loans (
    id_loan     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user     BIGINT NOT NULL,
    id_book     BIGINT NOT NULL,
    id_branch   BIGINT NOT NULL,
    id_faculty  BIGINT,
    issued_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    returned_at TIMESTAMP,
    CONSTRAINT fk_book_loans_user FOREIGN KEY (id_user) REFERENCES app_users(id_user),
    CONSTRAINT fk_book_loans_book FOREIGN KEY (id_book) REFERENCES books(id_book),
    CONSTRAINT fk_book_loans_branch FOREIGN KEY (id_branch) REFERENCES branches(id_branch),
    CONSTRAINT fk_book_loans_faculty FOREIGN KEY (id_faculty) REFERENCES faculties(id_faculty)
);

CREATE INDEX idx_books_title ON books(title);
CREATE INDEX idx_inventory_book_branch ON inventory(id_book, id_branch);
CREATE INDEX idx_book_faculty_book_branch ON book_faculty(id_book, id_branch);
CREATE INDEX idx_book_loans_book ON book_loans(id_book);
CREATE INDEX idx_book_loans_user ON book_loans(id_user);

-- Таблица запросов на выдачу и возврат книг
-- Статусы: 'pending' - ожидает одобрения, 'approved' - одобрено, 'rejected' - отклонено
CREATE TABLE loan_requests (
    id_request     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user        BIGINT NOT NULL,
    id_book        BIGINT NOT NULL,
    id_branch      BIGINT NOT NULL,
    id_faculty     BIGINT,
    request_type   VARCHAR(10) NOT NULL, -- 'take' (взять) или 'return' (вернуть)
    status         VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at    TIMESTAMP,
    approved_by    BIGINT,
    CONSTRAINT fk_loan_requests_user FOREIGN KEY (id_user) REFERENCES app_users(id_user),
    CONSTRAINT fk_loan_requests_book FOREIGN KEY (id_book) REFERENCES books(id_book),
    CONSTRAINT fk_loan_requests_branch FOREIGN KEY (id_branch) REFERENCES branches(id_branch),
    CONSTRAINT fk_loan_requests_faculty FOREIGN KEY (id_faculty) REFERENCES faculties(id_faculty),
    CONSTRAINT fk_loan_requests_approved_by FOREIGN KEY (approved_by) REFERENCES app_users(id_user),
    CONSTRAINT ck_loan_requests_type CHECK (request_type IN ('take', 'return')),
    CONSTRAINT ck_loan_requests_status CHECK (status IN ('pending', 'approved', 'rejected'))
);

CREATE INDEX idx_loan_requests_user ON loan_requests(id_user);
CREATE INDEX idx_loan_requests_status ON loan_requests(status);
CREATE INDEX idx_loan_requests_branch ON loan_requests(id_branch);

