CREATE TABLE IF NOT EXISTS app_users (
    id_user       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(250) NOT NULL,
    email         VARCHAR(250) NOT NULL UNIQUE,
    password_salt VARCHAR(100) NOT NULL,
    password_hash VARCHAR(128) NOT NULL,
    role          VARCHAR(20) NOT NULL DEFAULT 'client',
    id_faculty    BIGINT,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_app_users_role CHECK (role IN ('client', 'admin')),
    CONSTRAINT fk_app_users_faculty FOREIGN KEY (id_faculty) REFERENCES faculties(id_faculty)
);

CREATE TABLE IF NOT EXISTS book_loans (
    id_loan     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user     BIGINT NOT NULL,
    id_book     BIGINT NOT NULL,
    id_branch   BIGINT NOT NULL,
    id_faculty  BIGINT,
    issued_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    returned_at TIMESTAMP,
    CONSTRAINT fk_book_loans_user FOREIGN KEY (id_user) REFERENCES app_users(id_user),
    CONSTRAINT fk_book_loans_book FOREIGN KEY (id_book) REFERENCES books(id_book),
    CONSTRAINT fk_book_loans_branch FOREIGN KEY (id_branch) REFERENCES branches(id_branch),
    CONSTRAINT fk_book_loans_faculty FOREIGN KEY (id_faculty) REFERENCES faculties(id_faculty)
);

CREATE INDEX IF NOT EXISTS idx_book_loans_book ON book_loans(id_book);
CREATE INDEX IF NOT EXISTS idx_book_loans_user ON book_loans(id_user);

INSERT INTO app_users(full_name, email, password_salt, password_hash, role, id_faculty)
SELECT 'Администратор библиотеки',
       'admin@example.com',
       'seed-admin',
       '34d9c5694eaa9c5fb2a38fafc8edebb8e0dd40c79d39369b7aa4db1fba4529d0',
       'admin',
       NULL
WHERE NOT EXISTS (SELECT 1 FROM app_users WHERE email = 'admin@example.com');

INSERT INTO app_users(full_name, email, password_salt, password_hash, role, id_faculty)
SELECT 'Иван Петров',
       'student@example.com',
       'seed-client',
       'd84b638445f265065153fc3b55f738817ef6680920d39ea6d2e7f0b3720e82c4',
       'client',
       f.id_faculty
FROM faculties f
WHERE f.name = 'ФКН'
  AND NOT EXISTS (SELECT 1 FROM app_users WHERE email = 'student@example.com');
